services:
  - type: web
    name: smart-service-token-backend
    env: python
    buildCommand: "npm install && npm run build && pip install -r requirements.txt"
    startCommand: gunicorn --bind 0.0.0.0:$PORT backend.app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SESSION_SECRET
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: MAIL_SERVER
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: "587"
      - key: MAIL_USERNAME
        sync: false
      - key: MAIL_PASSWORD
        sync: false
      - key: MAIL_DEFAULT_SENDER
        value: noreply@yourdomain.com
      - key: ADMIN_USERNAME
        value: admin
      - key: ADMIN_PASSWORD
        sync: false